version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  php:
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
    build: .
    container_name: php_web
    links: 
      - "db:database"
    depends_on:
      - db
    stdin_open: true
    tty: true